// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    repositories {
        google()
        mavenCentral()
        maven { url = uri('https://jitpack.io') }
    }
}

ext {
    minSdkVersion = 23
    targetSdkVersion = 36
    compileSdkVersion = 37
    okhttp3Version = '3.12.13'
}

subprojects {
    plugins.withId('com.android.base') {
        android {
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_21
                targetCompatibility = JavaVersion.VERSION_21
            }
        }
    }
}
