apply plugin: 'com.android.library'

base.archivesName = 'chuck-no-op'

android {
    namespace = 'com.readystatesoftware.chuck'
    compileSdk = rootProject.ext.compileSdkVersion
    defaultConfig {
        minSdk = rootProject.ext.minSdkVersion
    }
}

dependencies {
    api "com.squareup.okhttp3:okhttp:$rootProject.ext.okhttp3Version"
}

apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
